[package]
name = "tcpserver"
version = "0.1.0"
authors = ["Balits Peter Marton balits.peter@gmail.com"]
edition = "2024"

[dependencies]
env_logger = "0.11.8"
log = "0.4.27"
mio = { version = "1.0.4", features = ["net", "os-poll"] }
thiserror = "2.0.12"
